/*
 * AuthService
 * Для работы со swagger необходимо выполнить обязательный рест-запрос \"`/authorization`\". В результате этого запроса будет получен идентификатор сессии (sid) — обязательный параметр для других рест-запросов.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.aritmos.model.keycloak;

import com.fasterxml.jackson.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.serde.annotation.Serdeable;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.annotation.Generated;
import java.util.Objects;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/** AuthenticationCheckedRolePostRequest */
@Serdeable
@JsonPropertyOrder(AuthenticationCheckedRolePostRequest.JSON_PROPERTY_ROLE)
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AuthenticationCheckedRolePostRequest {

  public static final String JSON_PROPERTY_ROLE = "role";

  @Nullable(inherited = true)
  @Schema(name = "role", example = "operator", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
  private String role;

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationCheckedRolePostRequest authenticationCheckedRolePostRequest =
        (AuthenticationCheckedRolePostRequest) o;
    return Objects.equals(role, authenticationCheckedRolePostRequest.role);
  }

  @Override
  public int hashCode() {
    return Objects.hash(role);
  }

  @Override
  public String toString() {
    return "AuthenticationCheckedRolePostRequest(" + "role: " + getRole() + ")";
  }
}
