image: registry.aritmosplatform.ru/aritmosplatform/devops-admin/images/deploy:latest

include:
  - project: 'aritmosplatform/devops-admin/gitlab-ci-template'
    ref: main
    file: '.default-before-after-template.yml'

  - project: 'aritmosplatform/devops-admin/gitlab-ci-template'
    ref: main
    file: '.deploy-client-template.yml'

stages:
  - build
  - deploy

variables:

  USER: gitlab-ci-token
  PASS: $CI_JOB_TOKEN
  REGISTRY: $CI_REGISTRY
  REGISTRY_IMAGE: $CI_REGISTRY_IMAGE

Build images:
  variables:
    ENVIRONMENT: "dev"
  stage: build
  image: registry.aritmosplatform.ru/aritmosplatform/devops-admin/images/docker
  services:
    - name: registry.aritmosplatform.ru/aritmosplatform/devops-admin/images/docker:dind
      alias: docker
  script:
    - docker login -u $USER -p $PASS $REGISTRY
    - docker build --pull -t $REGISTRY_IMAGE:$ENVIRONMENT -f ./Dockerfile .
    - docker push $REGISTRY_IMAGE:$ENVIRONMENT
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_REF_NAME == "test" && $CI_PIPELINE_SOURCE == "push"
      variables:
        ENVIRONMENT: "test"
    - if: $CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE == "push"
      variables:
        USER: $DOCKER_HUB_USER
        PASS: $DOCKER_HUB_PASS
        REGISTRY: "https://index.docker.io/v1/"
        REGISTRY_IMAGE: "aritmosplatform/aritmos-platform"
        ENVIRONMENT: $CI_PROJECT_NAME-main

