

services:

  visitmanager:

    networks:
      - confluent
    container_name: visitmanager
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    image: aritmos/visitmanager:0.6
    depends_on:
       redis:
         condition: service_healthy
    environment:
      - REDIS_SERVER=redis://redis:6379/6
      - DATABUS_SERVER=http://192.168.8.45:8082
      - CONFIG_SERVER=http://localhost:8081
      - PRINTER_SERVER=http://192.168.3.33:8084
      - OIDC_ISSUER_DOMAIN=http://192.168.8.45:9090/realms/Aritmos
      - OAUTH_CLIENT_ID=myclient
      - KEYCLOAK_TECHLOGIN=visitmanager
      - KEYCLOAK_TECHPASSWORD=visitmanager
    restart: always
  redis:
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - confluent
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
networks:
  confluent:
    driver: bridge