application:
  api:
    swagger:
      path: /api-docs/swagger
      version: 3.19.4
      layout: StandaloneLayout
      deepLinking: true
      urls:
        - name: ubw-rest
          url: /api-docs/swagger/ubw-rest-0.1.yml
logger:
  levels: ALL
graphql:
  enabled: true
  graphiql: # enables the /graphiql endpoint to test calls against your graph.
    enabled: true
loki:
  url: '${LOKI_SERVER:`http://192.168.3.13:3100/loki/api/v1/push`}'

business-exception:
  localization:
    http:
      language: '${BUSINESS_EXCEPTION_HTTP_LANG:`ru`}'
      default-language: ru
    log:
      language: '${BUSINESS_EXCEPTION_LOG_LANG:`ru`}'
      default-language: ru
    event:
      language: '${BUSINESS_EXCEPTION_EVENT_LANG:`ru`}'
      default-language: ru


micronaut:
  test:
    resources:
      enabled: false
  http:
    client:
      pool:
        enabled: true
        max-connections: 2000           # под нагрузку
        acquire-timeout: 2s
      read-timeout: 3s
      connect-timeout: 2s
      # HTTP/2 = больше запросов на одно соединение
      http2: true
  metrics:
    enabled: true
  server:
    port: 8080
    cors:
      enabled: true
  application:
    rules:

      callRuleApiUrl: http://localhost:8085/customcallrule
    returnTimeDelay: 8000
    name: visitmanager
    dataBusUrl: '${DATABUS_SERVER:`http://192.168.8.45:8082`}'
    #dataBusUrl: '${DATABUS_SERVER}'
    dataBusUrlRetryPeriod: '1s'
    dataBusUrlRetryMaxPeriod: '45m'
    dataBusUrlRetryRepeat: 3000
    configurationURL: '${CONFIG_SERVER:`http://localhost:8081`}'
    printerServiceURL: '${PRINTER_SERVER:`http://192.168.3.29:8084`}'
    printerRetryPeriod: '1s'
    printerRetryMaxPeriod: '45m'
    printerRetryRepeat: 30
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

endpoints:
  all:
    enabled: true
    path: /management/
    sensitive: false
  beans:
    enabled: true
  caches:
    enabled: true
  env:
    enabled: true
  health:
    enabled: true
    details-visible: ANONYMOUS
  info:
    enabled: true
  loggers:
    enabled: true
  metrics:
    enabled: true
  refresh:
    enabled: true
  routes:
    enabled: true
  stop:
    enabled: true
  threaddump:
    enabled: true

