#tag::port[]
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: 8080
#end::port[]
---
#tag::oauth2[]
micronaut:
  security:
    authentication: cookie

    intercept-url-map:
      - pattern: /swagger-ui/*
        access:
          - isAuthenticated()
      - pattern: /entrypoint/**
        access:
          - isAuthenticated()
      - pattern: /servicepoint/**
        access:
          - isAuthenticated()
      - pattern: /swagger-ui/**
        access:
          - isAuthenticated()
      - pattern: /swagger/**
        access:
          - isAuthenticated()

      - pattern: /oauth/login/keycloak
        access:
          - isAnonymous()

    oauth2:
      clients:
        keycloak:
          techlogin: '${KEYCLOAK_TECHLOGIN:visitmanager}'
          techpassword: '${KEYCLOAK_TECHPASSWORD:visitmanager}'
          keycloakurl: '${OIDC_ISSUER_URL:`http://192.168.8.45:9090`}'
          realm: Aritmos
          token:
            auth-method: client_secret_post
          client-secret: '${OAUTH_CLIENT_SECRET:Z1s7zHauY29ZLyhPS2fKvvoWFOSjfPYG}' # <3>
          client-id: '${OAUTH_CLIENT_ID:myclient}' # <4>
          openid:
            issuer: '${OIDC_ISSUER_DOMAIN:`http://192.168.8.45:9090`}/realms/${KEYCLOAK_REALM:aritmos_platform}' # <5>

    endpoints:
      logout:
        get-allowed: true # <6>
    enabled: false
#end::oauth2[]

graphql:
  enabled: true
  graphiql.enabled: true
  graphql-ws.enabled: true