#tag::port[]
micronaut:
  server:
    port: 8080
#end::port[]
---
#tag::oauth2[]
micronaut:
  security:
    authentication: cookie

    intercept-url-map:
      - pattern: /swagger-ui/*
        access:
          - isAuthenticated()
      - pattern: /entrypoint/**
        access:
          - isAuthenticated()
      - pattern: /servicepoint/**
        access:
          - isAuthenticated()
      - pattern: /swagger-ui/**
        access:
          - isAuthenticated()
      - pattern: /swagger/**
        access:
          - isAuthenticated()

      - pattern: /oauth/login/keycloak
        access:
          - isAnonymous()

    oauth2:
      clients:
        keycloak: # <2>
          token:
            auth-method: client_secret_post
          client-secret: '${OAUTH_CLIENT_SECRET:MrRPUXQlckY451gnYklvHEWGeciLlukn}' # <3>
          client-id: '${OAUTH_CLIENT_ID:myclient}' # <4>
          openid:
            issuer: '${OIDC_ISSUER_DOMAIN:`http://192.168.8.45:9090`}/realms/${KEYCLOAK_REALM:Aritmos}' # <5>

    endpoints:
      logout:
        get-allowed: true # <6>
    enabled: true
#end::oauth2[]

graphql:
  enabled: true
  graphiql.enabled: true
  graphql-ws.enabled: true