business-exception:
  localization:
    http:
      language: '${BUSINESS_EXCEPTION_HTTP_LANG:`en`}'
      default-language: en
    log:
      language: '${BUSINESS_EXCEPTION_LOG_LANG:`ru`}'
      default-language: ru
    event:
      language: '${BUSINESS_EXCEPTION_EVENT_LANG:`ru`}'
      default-language: ru

#tag::port[]
micronaut:
  http:
    client:
      pool:
        enabled: true
        max-connections: 2000           # под нагрузку
        acquire-timeout: 2s
      read-timeout: 3s
      connect-timeout: 2s
      # HTTP/2 = больше запросов на одно соединение
      http2: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: 8080
#end::port[]
---
#tag::oauth2[]
micronaut:
  metrics:
    enabled: true
  security:
    authentication: cookie

    intercept-url-map:
      - pattern: /swagger-ui/*
        access:
          - isAuthenticated()
      - pattern: /entrypoint/**
        access:
          - isAuthenticated()
      - pattern: /servicepoint/**
        access:
          - isAuthenticated()
      - pattern: /swagger-ui/**
        access:
          - isAuthenticated()
      - pattern: /swagger/**
        access:
          - isAuthenticated()

      - pattern: /oauth/login/keycloak
        access:
          - isAnonymous()

      - pattern: /management/**
        access:
          - isAnonymous()

    oauth2:
      clients:
        keycloak:
          techlogin: '${KEYCLOAK_TECHLOGIN:admin}'
          techpassword: '${KEYCLOAK_TECHPASSWORD:LtlVjhjp!23}'
          keycloakurl: '${OIDC_ISSUER_URL:`http://192.168.8.40:8282`}'
          realm: aritmos_platform
          token:
            auth-method: client_secret_post
          client-secret: '${OAUTH_CLIENT_SECRET:A7gpRkCOcdjEucoqodkPpE79cWaqLIOg}' # <3>
          client-id: '${OAUTH_CLIENT_ID:auth_service}' # <4>
          openid:
            issuer: '${OIDC_ISSUER_DOMAIN:`http://192.168.8.40:8282`}/realms/${KEYCLOAK_REALM:aritmos_platform}' # <5>

    endpoints:
      all:
        enabled: true
        prometheus:
          enabled: true    # GET /prometheus
        metrics:
          enabled: true    # GET /metrics (JSON)
      micrometer:
        enabled: true
        binders:
          web:
            enabled: true
        exporters:
          prometheus:
            enabled: true
      logout:
        get-allowed: true # <6>
    enabled: false

#end::oauth2[]

graphql:
  enabled: true
  graphiql.enabled: true
  graphql-ws.enabled: true
