business-exception:
  localization:
    http:
      language: '${BUSINESS_EXCEPTION_HTTP_LANG:`en`}'
      default-language: en
    log:
      language: '${BUSINESS_EXCEPTION_LOG_LANG:`ru`}'
      default-language: ru
    event:
      language: '${BUSINESS_EXCEPTION_EVENT_LANG:`ru`}'
      default-language: ru

kafka:
  consumers:
    default:
      allow.auto.create.topics: true
  producers:
    default:
      allow.auto.create.topics: true
  bootstrap:
    servers: '${KAFKA_SERVER:`192.168.8.45:29092`}'

redis:
  uri: '${REDIS_SERVER:`redis://192.168.8.45:7379`}'
  caches:
    branches:
      charset: UTF-8
      key-serializer: io.micronaut.core.serialize.ObjectSerializer
      value-serializer: io.micronaut.core.serialize.ObjectSerializer
      expire-after-write: 1h  # Время жизни записи
      expire-after-access: 30m # Время жизни после последнего доступа
      maximum-size: 1000       # Максимальное количество записей
