@startuml
!include style.puml
actor Operator
actor Client
participant API as "ServicePointController"
participant Visit as "VisitService"
queue Kafka

Operator -> API: POST /servicepoint/.../confirmed/visits/call
API -> Visit: callNextVisitForConfirm(...)
Visit -> Kafka: VISIT_CALLED
Visit --> API: Visit{id}
API --> Operator: 200 + Visit
Client -> API: POST /servicepoint/.../visits/servicePoints/{spId}/confirmed/confirm/{visitId}
API -> Visit: visitConfirm(...)
Visit -> Kafka: VISIT_CONFIRMED
API --> Client: 200 OK
@enduml
