@startuml
!include style.puml
left to right direction
actor Client
actor Operator
Client --> (Создать визит)
Client --> (Получить талон)
Client --> (Отменить визит)
Client --> (Проверить статус)
Operator --> (Открыть точку)
Operator --> (Вызвать визит)
Operator --> (Подтвердить/Завершить визит)
Operator --> (Перевести визит)
@enduml
