@startuml
!include style.puml

title Жизненный цикл визита и связанные события

state "Создан\n(CREATED)" as Created
state "В очереди ожидания\n(WAITING_IN_QUEUE)" as WaitingQueue
state "Вызван\n(CALLED)" as Called
state "Обслуживается\n(SERVING)" as Serving
state "Ожидает сотрудника\n(WAITING_IN_USER_POOL)" as WaitingUser
state "Ожидает точку обслуживания\n(WAITING_IN_SERVICE_POOL)" as WaitingService
state "Завершён\n(END)" as End

[*] --> Created : CREATED
Created --> WaitingQueue : PLACED_IN_QUEUE
Created --> Called : CALLED / RECALLED

WaitingQueue --> Called : CALLED / RECALLED
WaitingQueue --> WaitingUser : TRANSFER_TO_USER_POOL
WaitingQueue --> WaitingService : TRANSFER_TO_SERVICE_POINT_POOL
WaitingQueue --> End : NO_SHOW / END / DELETED

Called --> Serving : START_SERVING
Called --> WaitingQueue : BACK_TO_QUEUE / TRANSFER_TO_QUEUE
Called --> WaitingUser : TRANSFER_TO_USER_POOL / BACK_TO_USER_POOL
Called --> WaitingService : TRANSFER_TO_SERVICE_POINT_POOL / BACK_TO_SERVICE_POINT_POOL
Called --> End : NO_SHOW / END / DELETED

Serving --> Called : CALLED / RECALLED
Serving --> WaitingQueue : TRANSFER_TO_QUEUE
Serving --> WaitingUser : TRANSFER_TO_USER_POOL
Serving --> WaitingService : TRANSFER_TO_SERVICE_POINT_POOL
Serving --> End : END / DELETED

WaitingUser --> Called : CALLED / RECALLED
WaitingUser --> WaitingService : TRANSFER_TO_SERVICE_POINT_POOL / BACK_TO_SERVICE_POINT_POOL
WaitingUser --> End : END / DELETED

WaitingService --> Called : CALLED / RECALLED
WaitingService --> WaitingUser : TRANSFER_TO_USER_POOL / BACK_TO_USER_POOL
WaitingService --> End : END / DELETED

note right of Serving
  События без смены состояния:
  * ADD_SERVICE
  * ADDED_DELIVERED_SERVICE
  * ADDED_DELIVERED_SERVICE_RESULT
  * ADDED_SERVICE_RESULT
  * ADDED_MARK
  * ADDED_NOTE
  * DELETED_MARK
  * DELETED_DELIVERED_SERVICE
  * DELETED_DELIVERED_SERVICE_RESULT
  * DELETED_SERVICE_RESULT
  * STOP_SERVING
end note

note bottom of End
  Также фиксируются системные события VISIT_END_TRANSACTION
  и VISIT_TRANSFER_FROM_QUEUE без изменения состояния визита.
end note

End --> [*]
@enduml
